// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringAgent.Web.Data;

#nullable disable

namespace MonitoringAgent.Web.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260407084417_AddDiskTestLogTable")]
    partial class AddDiskTestLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringAgent.Web.Data.AlertRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("float");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ImpactScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.BlockingEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockedQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockedResource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockedSpid")
                        .HasColumnType("int");

                    b.Property<string>("BlockingQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlockingSpid")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WaitTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("WaitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlockingEvents");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.DatabaseMetricRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveSessions")
                        .HasColumnType("int");

                    b.Property<double>("AvgReadLatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgWriteLatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("DataFileSpaceFreeMb")
                        .HasColumnType("float");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DatabaseSizeMb")
                        .HasColumnType("float");

                    b.Property<int>("DaysSinceLastBackup")
                        .HasColumnType("int");

                    b.Property<bool>("HasPercentGrowth")
                        .HasColumnType("bit");

                    b.Property<long>("IoReadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("IoReadLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<long>("IoWriteBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("IoWriteLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAutoCloseOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoShrinkOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrustworthyOn")
                        .HasColumnType("bit");

                    b.Property<double>("LogFileSpaceFreeMb")
                        .HasColumnType("float");

                    b.Property<double>("LogSizeMb")
                        .HasColumnType("float");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("VlfCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DatabaseMetrics");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.DeadlockEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeadlockGraphXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeadlockEvents");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.DiskTestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockSizeKB")
                        .HasColumnType("int");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("float");

                    b.Property<int>("DurationSec")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileSizeGB")
                        .HasColumnType("int");

                    b.Property<double>("IOPS")
                        .HasColumnType("float");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("MBps")
                        .HasColumnType("float");

                    b.Property<int>("QueueDepth")
                        .HasColumnType("int");

                    b.Property<string>("RawOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("TestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<int>("WritePercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiskTestLogs");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.IndexIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FragmentationPercent")
                        .HasColumnType("float");

                    b.Property<decimal>("ImpactScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PageCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndexIssues");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.InstanceMetricRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BatchRequestsPerSec")
                        .HasColumnType("bigint");

                    b.Property<double>("BufferCacheHitRatio")
                        .HasColumnType("float");

                    b.Property<int>("CostThresholdForParallelism")
                        .HasColumnType("int");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("float");

                    b.Property<int>("FailedLoginsLastMinute")
                        .HasColumnType("int");

                    b.Property<int>("MaxDop")
                        .HasColumnType("int");

                    b.Property<double>("MemoryTargetMb")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsageMb")
                        .HasColumnType("float");

                    b.Property<long>("PLE")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SqlCpuUsagePercent")
                        .HasColumnType("float");

                    b.Property<double>("SqlMemoryUsageMb")
                        .HasColumnType("float");

                    b.Property<int>("SysAdminCount")
                        .HasColumnType("int");

                    b.Property<double>("TempDbLogSizeMb")
                        .HasColumnType("float");

                    b.Property<double>("TempDbSizeMb")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalConnections")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("InstanceMetrics");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.PayloadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payloads");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.QueryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgCpuTimeUs")
                        .HasColumnType("float");

                    b.Property<double>("AvgElapsedTimeUs")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalElapsedTimeUs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLogicalReads")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLogicalWrites")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalPhysicalReads")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalWorkerTimeUs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.TargetServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludeDBs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TargetServers");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.WaitStatRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstanceMetricRecordId")
                        .HasColumnType("int");

                    b.Property<long>("MaxWaitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SignalWaitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<long>("WaitCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WaitTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("WaitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceMetricRecordId");

                    b.ToTable("WaitStats");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.WorkerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvancedControlsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcludeDBs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureTogglesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludeDBs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexAnalysisJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntervalsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoggingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerConfigs");
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.WaitStatRecord", b =>
                {
                    b.HasOne("MonitoringAgent.Web.Data.InstanceMetricRecord", null)
                        .WithMany("TopWaitStats")
                        .HasForeignKey("InstanceMetricRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitoringAgent.Web.Data.InstanceMetricRecord", b =>
                {
                    b.Navigation("TopWaitStats");
                });
#pragma warning restore 612, 618
        }
    }
}
